import { mockReadings } from './mockData';
import type { Reading, CreateReadingDTO, UpdateReadingDTO, AIGenerateRequest, AIGeneratedReading } from '../types';
import { ReadingDifficulty } from '../types';

const delay = (ms = 500) => new Promise(res => setTimeout(res, ms));

let readings = [...mockReadings];

export const readingApi = {
  getAll: async (): Promise<Reading[]> => {
    await delay();
    return [...readings];
  },

  getById: async (id: string): Promise<Reading> => {
    await delay();
    const r = readings.find(item => item.id === id);
    if (!r) throw new Error('Reading not found');
    return { ...r };
  },

  create: async (dto: CreateReadingDTO): Promise<Reading> => {
    await delay();
    const newReading: Reading = {
      id: `r_${Date.now()}`,
      ...dto,
      topicName: undefined,
      questions: dto.questions.map((q, i) => ({ ...q, id: `q_${Date.now()}_${i}` })),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    readings = [...readings, newReading];
    return newReading;
  },

  update: async (id: string, dto: UpdateReadingDTO): Promise<Reading> => {
    await delay();
    const index = readings.findIndex(r => r.id === id);
    if (index === -1) throw new Error('Reading not found');
    const updated: Reading = {
      ...readings[index],
      ...dto,
      questions: dto.questions
        ? dto.questions.map((q, i) => ({ ...q, id: (q as any).id || `q_${Date.now()}_${i}` }))
        : readings[index].questions,
      updatedAt: new Date().toISOString(),
    };
    readings = readings.map(r => r.id === id ? updated : r);
    return updated;
  },

  delete: async (id: string): Promise<void> => {
    await delay();
    readings = readings.filter(r => r.id !== id);
  },

  generateWithAI: async (request: AIGenerateRequest): Promise<AIGeneratedReading> => {
    await delay(1500);
    return {
      title: `AI Generated: ${request.prompt}`,
      paragraph: `This is an AI-generated reading passage about "${request.prompt}". The passage would contain rich vocabulary, natural language patterns, and educational content appropriate for the requested level. In a real implementation, this would be generated by an AI model like GPT-4 or Gemini, providing authentic, contextual content tailored to the learner's needs. The text would include varied sentence structures, idiomatic expressions, and topic-specific vocabulary that enhances the learning experience.`,
      translation: `Đây là đoạn văn được tạo bởi AI về chủ đề "${request.prompt}". Trong phiên bản thực, nội dung này sẽ được tạo bởi một mô hình AI như GPT-4 hoặc Gemini.`,
      difficulty: ReadingDifficulty.B1,
      estimatedMinutes: 3,
      vocabularyHighlights: ['generated', 'authentic', 'contextual', 'idiomatic', 'vocabulary'],
      questions: [
        {
          question: `What is the main topic of this passage?`,
          choices: [request.prompt, 'Science', 'History', 'Sports'],
          correctAnswer: 0,
          explanation: `The passage is clearly about "${request.prompt}" as stated in the prompt.`,
        },
        {
          question: 'What type of content does AI generation provide?',
          choices: ['Static content', 'Random text', 'Authentic contextual content', 'Copied text'],
          correctAnswer: 2,
          explanation: 'The passage states AI provides "authentic, contextual content tailored to the learner\'s needs".',
        },
      ],
    };
  },
};
